// <auto-generated />
using System;
using BaseballECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseballECommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250301155241_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseballEcommerce.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d4c053-49b6-410c-bc78-2d54a9991871"),
                            Name = "Baseball Caps"
                        },
                        new
                        {
                            Id = new Guid("b2e5a070-94ce-4d15-9494-5248280c2ce4"),
                            Name = "Memorabilia"
                        },
                        new
                        {
                            Id = new Guid("c3f6b090-24de-4f25-9895-1234567a2bc5"),
                            Name = "Baseball Jerseys"
                        });
                });

            modelBuilder.Entity("BaseballEcommerce.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f6b090-24de-4f25-9895-1234567a2bc5"),
                            CategoryId = new Guid("c3f6b090-24de-4f25-9895-1234567a2bc5"),
                            Description = "Stanimal wore this jersey when he played for NYCSummerBaseball Giants in 2022.",
                            ImageUrl = "https://example.com/images/stamimal-giants-jersey.jpg",
                            ListPrice = 50.0,
                            Name = "Stanimal Giants Jersey",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b2e5a070-94ce-4d15-9494-5248280c2ce4"),
                            CategoryId = new Guid("b2e5a070-94ce-4d15-9494-5248280c2ce4"),
                            Description = "This gnome was given out as part of a Mets game giveaway.",
                            ImageUrl = "https://example.com/images/lindor-garden-gnome-2023.jpg",
                            ListPrice = 50.0,
                            Name = "Francisco Lindor Garden Gnome",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("BaseballEcommerce.Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("BaseballEcommerce.Core.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BaseballEcommerce.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
